language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"

install:
  - "pip install flake8"
  - "python setup.py install"

before_script:
  - "flake8 s_tui"

script:
  - "python -m s_tui.Tests.test_util_source"
  - "s-tui -t"
  - "s-tui -j"
  - "s-tui -dr"
